# SPDX-License-Identifier: BSL-1.0
# SPDX-FileCopyrightText: Copyright (C) 2023 Tobias Hienzsch
ignore:
  - "include/etl/_3rd_party"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        informational: true
