// SPDX-License-Identifier: BSL-1.0
// SPDX-FileCopyrightText: Copyright (C) 2025 Tobias Hienzsch

export namespace etl {

using etl::array;
using etl::operator==;
using etl::get;
using etl::swap;
using etl::to_array;
using etl::tuple_element;
using etl::tuple_element_t;
using etl::tuple_size;
using etl::tuple_size_v;

// Non-standard extensions
using etl::c_array;
using etl::dynamic_array;
using etl::uninitialized_array;

} // namespace etl
