// SPDX-License-Identifier: BSL-1.0
// SPDX-FileCopyrightText: Copyright (C) 2025 Tobias Hienzsch

export namespace etl {

using etl::atof;
using etl::atoi;
using etl::atol;
using etl::atoll;
using etl::div;
using etl::div_t;
using etl::imaxdiv;
using etl::imaxdiv_t;
using etl::labs;
using etl::ldiv;
using etl::ldiv_t;
using etl::llabs;
using etl::lldiv;
using etl::lldiv_t;
using etl::nullptr_t;
using etl::size_t;
using etl::strtod;
using etl::strtof;
using etl::strtol;
using etl::strtold;
using etl::strtoul;

} // namespace etl
