// SPDX-License-Identifier: BSL-1.0
// SPDX-FileCopyrightText: Copyright (C) 2025 Tobias Hienzsch

export namespace etl {

using etl::int16_t;
using etl::int32_t;
using etl::int64_t;
using etl::int8_t;
using etl::int_fast16_t;
using etl::int_fast32_t;
using etl::int_fast64_t;
using etl::int_fast8_t;
using etl::int_least16_t;
using etl::int_least32_t;
using etl::int_least64_t;
using etl::int_least8_t;
using etl::intmax_t;
using etl::intptr_t;
using etl::uint128;
using etl::uint128_t;
using etl::uint16_t;
using etl::uint32_t;
using etl::uint64_t;
using etl::uint8_t;
using etl::uint_fast16_t;
using etl::uint_fast32_t;
using etl::uint_fast64_t;
using etl::uint_fast8_t;
using etl::uint_least16_t;
using etl::uint_least32_t;
using etl::uint_least64_t;
using etl::uint_least8_t;
using etl::uintmax_t;
using etl::uintptr_t;

} // namespace etl
