
export namespace etl {

using etl::wcscat;
using etl::wcschr;
using etl::wcscmp;
using etl::wcscpy;
using etl::wcscspn;
using etl::wcslen;
using etl::wcsncat;
using etl::wcsncmp;
using etl::wcsncpy;
using etl::wcspbrk;
using etl::wcsrchr;
using etl::wcsspn;
using etl::wcsstr;
using etl::wint_t;
using etl::wmemchr;
using etl::wmemcmp;
using etl::wmemcpy;
using etl::wmemmove;
using etl::wmemset;

} // namespace etl
