module;

#include <etl/algorithm.hpp>
#include <etl/array.hpp>
#include <etl/bit.hpp>
#include <etl/bitset.hpp>
#include <etl/cctype.hpp>
#include <etl/cfloat.hpp>
#include <etl/charconv.hpp>
#include <etl/chrono.hpp>
#include <etl/cmath.hpp>
#include <etl/compare.hpp>
#include <etl/complex.hpp>
#include <etl/concepts.hpp>
#include <etl/cstddef.hpp>
#include <etl/cstdint.hpp>
#include <etl/cstdlib.hpp>
#include <etl/cstring.hpp>
#include <etl/cwchar.hpp>
#include <etl/exception.hpp>
#include <etl/execution.hpp>
#include <etl/expected.hpp>
#include <etl/flat_set.hpp>
#include <etl/functional.hpp>
#include <etl/inplace_vector.hpp>
#include <etl/iterator.hpp>
#include <etl/limits.hpp>
#include <etl/linalg.hpp>
#include <etl/mdarray.hpp>
#include <etl/mdspan.hpp>
#include <etl/memory.hpp>
#include <etl/meta.hpp>
#include <etl/mutex.hpp>
#include <etl/numbers.hpp>
#include <etl/numeric.hpp>
#include <etl/optional.hpp>
#include <etl/random.hpp>
#include <etl/ranges.hpp>
#include <etl/ratio.hpp>
#include <etl/scope.hpp>
#include <etl/set.hpp>
#include <etl/span.hpp>
#include <etl/stack.hpp>
#include <etl/stdexcept.hpp>
#include <etl/string.hpp>
#include <etl/string_view.hpp>
#include <etl/strings.hpp>
#include <etl/system_error.hpp>
#include <etl/tuple.hpp>
#include <etl/type_traits.hpp>
#include <etl/utility.hpp>
#include <etl/variant.hpp>
#include <etl/vector.hpp>
#include <etl/version.hpp>

export module etl;

#include "src/algorithm.inc"
#include "src/array.inc"
#include "src/bit.inc"
#include "src/bitset.inc"
#include "src/cctype.inc"
#include "src/cfloat.inc"
#include "src/charconv.inc"
#include "src/chrono.inc"
#include "src/cmath.inc"
#include "src/compare.inc"
#include "src/complex.inc"
#include "src/concepts.inc"
#include "src/cstddef.inc"
#include "src/cstdint.inc"
#include "src/cstdlib.inc"
#include "src/cstring.inc"
#include "src/cwchar.inc"
#include "src/exception.inc"
#include "src/execution.inc"
#include "src/expected.inc"
#include "src/flat_set.inc"
#include "src/functional.inc"
#include "src/inplace_vector.inc"
#include "src/iterator.inc"
#include "src/limits.inc"
#include "src/linalg.inc"
#include "src/mdarray.inc"
#include "src/mdspan.inc"
#include "src/memory.inc"
#include "src/meta.inc"
#include "src/mutex.inc"
#include "src/numbers.inc"
#include "src/numeric.inc"
#include "src/optional.inc"
#include "src/random.inc"
#include "src/ranges.inc"
#include "src/ratio.inc"
#include "src/scope.inc"
#include "src/set.inc"
#include "src/span.inc"
#include "src/stack.inc"
#include "src/stdexcept.inc"
#include "src/string.inc"
#include "src/string_view.inc"
#include "src/strings.inc"
#include "src/system_error.inc"
#include "src/tuple.inc"
#include "src/type_traits.inc"
#include "src/utility.inc"
#include "src/variant.inc"
#include "src/vector.inc"
#include "src/version.inc"
