/// \copyright Tobias Hienzsch 2019-2021
/// Distributed under the Boost Software License, Version 1.0.
/// See accompanying file LICENSE or copy at http://boost.org/LICENSE_1_0.txt

#ifndef TETL_ALGORITHM_HPP
#define TETL_ALGORITHM_HPP

/// \file This header is part of the algorithm library.
/// \example algorithm.cpp

#include "etl/_config/all.hpp"

#include "etl/_algorithm/adjacent_find.hpp"
#include "etl/_algorithm/all_of.hpp"
#include "etl/_algorithm/any_of.hpp"
#include "etl/_algorithm/binary_search.hpp"
#include "etl/_algorithm/clamp.hpp"
#include "etl/_algorithm/copy.hpp"
#include "etl/_algorithm/copy_backward.hpp"
#include "etl/_algorithm/copy_if.hpp"
#include "etl/_algorithm/copy_n.hpp"
#include "etl/_algorithm/count.hpp"
#include "etl/_algorithm/count_if.hpp"
#include "etl/_algorithm/equal.hpp"
#include "etl/_algorithm/equal_range.hpp"
#include "etl/_algorithm/fill.hpp"
#include "etl/_algorithm/fill_n.hpp"
#include "etl/_algorithm/find.hpp"
#include "etl/_algorithm/find_end.hpp"
#include "etl/_algorithm/find_first_of.hpp"
#include "etl/_algorithm/find_if.hpp"
#include "etl/_algorithm/find_if_not.hpp"
#include "etl/_algorithm/for_each.hpp"
#include "etl/_algorithm/for_each_n.hpp"
#include "etl/_algorithm/generate.hpp"
#include "etl/_algorithm/generate_n.hpp"
#include "etl/_algorithm/includes.hpp"
#include "etl/_algorithm/is_partitioned.hpp"
#include "etl/_algorithm/is_permutation.hpp"
#include "etl/_algorithm/is_sorted.hpp"
#include "etl/_algorithm/is_sorted_until.hpp"
#include "etl/_algorithm/iter_swap.hpp"
#include "etl/_algorithm/lexicographical_compare.hpp"
#include "etl/_algorithm/lower_bound.hpp"
#include "etl/_algorithm/max.hpp"
#include "etl/_algorithm/max_element.hpp"
#include "etl/_algorithm/merge.hpp"
#include "etl/_algorithm/min.hpp"
#include "etl/_algorithm/min_element.hpp"
#include "etl/_algorithm/minmax.hpp"
#include "etl/_algorithm/minmax_element.hpp"
#include "etl/_algorithm/mismatch.hpp"
#include "etl/_algorithm/move.hpp"
#include "etl/_algorithm/move_backward.hpp"
#include "etl/_algorithm/none_of.hpp"
#include "etl/_algorithm/nth_element.hpp"
#include "etl/_algorithm/partial_sort.hpp"
#include "etl/_algorithm/partition.hpp"
#include "etl/_algorithm/partition_copy.hpp"
#include "etl/_algorithm/partition_point.hpp"
#include "etl/_algorithm/remove.hpp"
#include "etl/_algorithm/remove_copy.hpp"
#include "etl/_algorithm/remove_copy_if.hpp"
#include "etl/_algorithm/remove_if.hpp"
#include "etl/_algorithm/replace.hpp"
#include "etl/_algorithm/replace_if.hpp"
#include "etl/_algorithm/reverse.hpp"
#include "etl/_algorithm/reverse_copy.hpp"
#include "etl/_algorithm/rotate.hpp"
#include "etl/_algorithm/rotate_copy.hpp"
#include "etl/_algorithm/search.hpp"
#include "etl/_algorithm/search_n.hpp"
#include "etl/_algorithm/set_difference.hpp"
#include "etl/_algorithm/set_intersection.hpp"
#include "etl/_algorithm/set_symmetric_difference.hpp"
#include "etl/_algorithm/set_union.hpp"
#include "etl/_algorithm/shift_left.hpp"
#include "etl/_algorithm/sort.hpp"
#include "etl/_algorithm/stable_partition.hpp"
#include "etl/_algorithm/stable_sort.hpp"
#include "etl/_algorithm/swap_ranges.hpp"
#include "etl/_algorithm/transform.hpp"
#include "etl/_algorithm/unique.hpp"
#include "etl/_algorithm/unique_copy.hpp"
#include "etl/_algorithm/upper_bound.hpp"

#endif // TETL_ALGORITHM_HPP