module;

#include <etl/algorithm.hpp>
#include <etl/array.hpp>
#include <etl/bit.hpp>
#include <etl/bitset.hpp>
#include <etl/cctype.hpp>
#include <etl/cfloat.hpp>
#include <etl/charconv.hpp>
#include <etl/chrono.hpp>
#include <etl/cmath.hpp>
#include <etl/compare.hpp>
#include <etl/complex.hpp>
#include <etl/concepts.hpp>
#include <etl/cstddef.hpp>
#include <etl/cstdint.hpp>
#include <etl/cstdlib.hpp>
#include <etl/cstring.hpp>
#include <etl/cwchar.hpp>
#include <etl/exception.hpp>
#include <etl/execution.hpp>
#include <etl/expected.hpp>
#include <etl/flat_set.hpp>
#include <etl/functional.hpp>
#include <etl/inplace_vector.hpp>
#include <etl/iterator.hpp>
#include <etl/limits.hpp>
#include <etl/linalg.hpp>
#include <etl/mdarray.hpp>
#include <etl/mdspan.hpp>
#include <etl/memory.hpp>
#include <etl/meta.hpp>
#include <etl/mutex.hpp>
#include <etl/numbers.hpp>
#include <etl/numeric.hpp>
#include <etl/optional.hpp>
#include <etl/random.hpp>
#include <etl/ranges.hpp>
#include <etl/ratio.hpp>
#include <etl/scope.hpp>
#include <etl/set.hpp>
#include <etl/source_location.hpp>
#include <etl/span.hpp>
#include <etl/stack.hpp>
#include <etl/stdexcept.hpp>
#include <etl/string.hpp>
#include <etl/string_view.hpp>
#include <etl/strings.hpp>
#include <etl/system_error.hpp>
#include <etl/tuple.hpp>
#include <etl/type_traits.hpp>
#include <etl/utility.hpp>
#include <etl/variant.hpp>
#include <etl/vector.hpp>
#include <etl/version.hpp>

#include <etl/experimental/freertos/queue.hpp>
#include <etl/experimental/freertos/stream_buffer.hpp>
#include <etl/experimental/freertos/task.hpp>

#include <etl/experimental/hardware/stm32/gpio.hpp>
#include <etl/experimental/hardware/stm32/interrupt.hpp>

#include <etl/experimental/net/buffer.hpp>
#include <etl/experimental/net/byte_order.hpp>

export module etl;

#include "inc/algorithm.inc"
#include "inc/array.inc"
#include "inc/bit.inc"
#include "inc/bitset.inc"
#include "inc/cctype.inc"
#include "inc/cfloat.inc"
#include "inc/charconv.inc"
#include "inc/chrono.inc"
#include "inc/cmath.inc"
#include "inc/compare.inc"
#include "inc/complex.inc"
#include "inc/concepts.inc"
#include "inc/cstddef.inc"
#include "inc/cstdint.inc"
#include "inc/cstdlib.inc"
#include "inc/cstring.inc"
#include "inc/cwchar.inc"
#include "inc/exception.inc"
#include "inc/execution.inc"
#include "inc/expected.inc"
#include "inc/flat_set.inc"
#include "inc/functional.inc"
#include "inc/inplace_vector.inc"
#include "inc/iterator.inc"
#include "inc/limits.inc"
#include "inc/linalg.inc"
#include "inc/mdarray.inc"
#include "inc/mdspan.inc"
#include "inc/memory.inc"
#include "inc/meta.inc"
#include "inc/mutex.inc"
#include "inc/numbers.inc"
#include "inc/numeric.inc"
#include "inc/optional.inc"
#include "inc/random.inc"
#include "inc/ranges.inc"
#include "inc/ratio.inc"
#include "inc/scope.inc"
#include "inc/set.inc"
#include "inc/source_location.inc"
#include "inc/span.inc"
#include "inc/stack.inc"
#include "inc/stdexcept.inc"
#include "inc/string.inc"
#include "inc/string_view.inc"
#include "inc/strings.inc"
#include "inc/system_error.inc"
#include "inc/tuple.inc"
#include "inc/type_traits.inc"
#include "inc/utility.inc"
#include "inc/variant.inc"
#include "inc/vector.inc"
#include "inc/version.inc"

#include "inc/experimental/freertos/queue.inc"
#include "inc/experimental/freertos/stream_buffer.inc"
#include "inc/experimental/freertos/task.inc"

#include "inc/experimental/hardware/stm32/gpio.inc"
#include "inc/experimental/hardware/stm32/interrupt.inc"

#include "inc/experimental/net/buffer.inc"
#include "inc/experimental/net/byte_order.inc"
