add_library(coverage_config INTERFACE)
add_library(tobanteAudio::CodeCoverage ALIAS coverage_config)

if(TOBANTEAUDIO_ETL_BUILD_COVERAGE AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  target_compile_options(coverage_config INTERFACE -O0 -g --coverage)
  if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.13)
    target_link_options(coverage_config INTERFACE --coverage)
  else()
    target_link_libraries(coverage_config INTERFACE --coverage)
  endif(CMAKE_VERSION VERSION_GREATER_EQUAL 3.13)
endif()