/// \copyright Tobias Hienzsch 2019-2021
/// Distributed under the Boost Software License, Version 1.0.
/// See accompanying file LICENSE or copy at http://boost.org/LICENSE_1_0.txt

#ifndef TETL_ALGORITHM_GENERATE_HPP
#define TETL_ALGORITHM_GENERATE_HPP

namespace etl {

/// \brief Assigns each element in range `[first, last)` a value generated by
/// the given function object g.
///
/// \param first The range of elements to generate.
/// \param last The range of elements to generate.
/// \param g Generator function object that will be called.
///
/// https://en.cppreference.com/w/cpp/algorithm/generate
template <typename ForwardIt, typename Generator>
constexpr auto generate(ForwardIt first, ForwardIt last, Generator g) -> void
{
    for (; first != last; ++first) { *first = g(); }
}

} // namespace etl

#endif // TETL_ALGORITHM_GENERATE_HPP