name: Benchmark Compile Time

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: [20, 23]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 17 all

      - name: Run benchmark build
        run: |
          cd benchmarks/compile
          python3 run.py "${{ matrix.cxx }}"
