name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [20, 23]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake lcov gcovr

      - name: Run coverage build
        run: CXX_STD="${{ matrix.cxx }}" make coverage-xml

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cmake-build-coverage/coverage.xml
          fail_ci_if_error: true
