# SPDX-License-Identifier: BSL-1.0
# SPDX-FileCopyrightText: Copyright (C) 2021 Tobias Hienzsch
name: Freestanding ARM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: alpine:edge
    strategy:
      matrix:
        cxx: [23, 26]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: >
          apk add
          cmake
          ninja
          gcc-arm-none-eabi
          g++-arm-none-eabi
          newlib-arm-none-eabi
          clang
          lld
          llvm
          llvm-linker-tools
          --no-cache

      - name: "GCC: Configure CMake"
        run: >
          cmake
          -S .
          -B cmake-build-gcc
          -G "Ninja Multi-Config"
          -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/gcc-arm-none-eabi.cmake
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON
          -D TETL_BUILD_CONTRACT_CHECKS=OFF

      - name: (GCC) Build -- Debug
        run: cmake --build cmake-build-gcc --config Debug

      - name: (GCC) Build -- Release
        run: cmake --build cmake-build-gcc --config Release

      - name: "Clang: Configure CMake"
        run: >
          cmake
          -S .
          -B cmake-build-clang
          -G "Ninja Multi-Config"
          -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/clang-arm-none-eabi.cmake
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON
          -D TETL_BUILD_CONTRACT_CHECKS=OFF

      - name: (Clang) Build -- Debug
        run: cmake --build cmake-build-clang --config Debug

      - name: (Clang) Build -- Release
        run: cmake --build cmake-build-clang --config Release
