name: Freestanding AVR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: alpine:edge
    strategy:
      matrix:
        cxx: [20, 23, 26]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add cmake ninja gcc-avr avr-libc --no-cache
          avr-g++ --version

      - name: Configure CMake
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/atmega2560.cmake
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D TETL_BUILD_WERROR=ON
          -D TETL_BUILD_CONTRACT_CHECKS=OFF

      - name: Build tests -- Debug
        run: cmake --build build --config Debug

      - name: Build tests -- Release
        run: cmake --build build --config Release
