name: Freestanding MSP430

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:latest
    strategy:
      matrix:
        cxx: [20, 23]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-msp430-elf g++-msp430-elf newlib-msp430-elf grep --no-cache
          grep --version
          msp430-elf-g++ --version

      - name: Build examples project (Debug)
        run: MSP430=1 CXXSTD=${{ matrix.cxx }} DEBUG=1 make -C examples clean all

      - name: Build examples project (Release)
        run: MSP430=1 CXXSTD=${{ matrix.cxx }} make -C examples clean all
