# SPDX-License-Identifier: BSL-1.0
# SPDX-FileCopyrightText: Copyright (C) 2021 Tobias Hienzsch
name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.config.image }}
    strategy:
      matrix:
        config: [
            { image: "macos-13", cxx: 23, arch: "x64", werror: "OFF" }, # -Wpre-c++2b-compat causes issues
            { image: "macos-15", cxx: 23, arch: "ARM64", werror: "OFF" }, # -Wpre-c++2b-compat causes issues
          ]
      fail-fast: false
    name: Xcode ${{ matrix.config.arch }} (C++${{ matrix.config.cxx }})
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: CMake configure
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_CXX_STANDARD=${{ matrix.config.cxx }}
          -D CMAKE_COMPILE_WARNING_AS_ERROR=${{ matrix.config.werror }}

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run tests -- Debug
        run: ctest --test-dir build -C Debug --output-on-failure

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run tests -- Release
        run: ctest --test-dir build -C Release --output-on-failure
