name: macOS

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.config.image }}
    strategy:
      matrix:
        config:
          [
            { image: "macos-13", cxx: 20, xcode: "latest-stable" },
            { image: "macos-14", cxx: 20, xcode: "latest" },
            { image: "macos-14", cxx: 23, xcode: "latest" },
          ]
      fail-fast: false
    name: Xcode ${{ matrix.config.xcode }} (C++${{ matrix.config.cxx }})
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.config.xcode }}

      - name: Install ninja
        run: brew install ninja

      - name: CMake configure
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_CXX_STANDARD=${{ matrix.config.cxx }}
          -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run tests -- Debug
        run: ctest --test-dir build -C Debug --output-on-failure

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run tests -- Release
        run: ctest --test-dir build -C Release --output-on-failure
