name: Pre-Commit Hooks

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Check
        run: |
          pre-commit run --all-files
