name: ASAN/UBSAN

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cxx: [20, 23, 26]
        flags:
          [
            { cmake: "-D TETL_BUILD_ASAN=ON", name: "ASAN" },
            { cmake: "-D TETL_BUILD_UBSAN=ON", name: "UBSAN" },
          ]
      fail-fast: false
    name: C++${{ matrix.cxx }} ${{ matrix.flags.name }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all

      - name: cmake configure
        run: >
          cmake -S .
          -B build
          -G Ninja
          -D CMAKE_BUILD_TYPE=Debug
          -D CMAKE_C_COMPILER=clang-18
          -D CMAKE_CXX_COMPILER=clang++-18
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
          ${{ matrix.flags.cmake }}

      - name: dump config
        run: cat build/compile_commands.json

      - name: cmake build
        run: cmake --build build

      - name: run tests
        run: ctest -VV --test-dir build -C Debug --output-on-failure
